export const metadata = {
    title: 'Terms of Service',
    description: 'The terms governing your use of False Nine.',
  }
  
  export default function TermsPage() {
    return (
      <>
        <style>{`
          @import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&display=swap');
          *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
          body { background-color: #080c10; color: #e8edf2; font-family: 'DM Sans', sans-serif; min-height: 100vh; }
          .app { max-width: 480px; margin: 0 auto; min-height: 100vh; background: #080c10; padding-bottom: 80px; }
          .header { padding: 56px 24px 24px; position: relative; }
          .header::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 200px; background: radial-gradient(ellipse at 50% -20%, rgba(0,200,100,0.15) 0%, transparent 70%); pointer-events: none; }
          .logo { font-family: 'Bebas Neue', sans-serif; font-size: 11px; letter-spacing: 4px; color: #00c864; text-transform: uppercase; margin-bottom: 4px; }
          .page-title { font-family: 'Bebas Neue', sans-serif; font-size: 48px; letter-spacing: 2px; line-height: 1; color: #ffffff; }
          .updated { font-size: 12px; color: #4a5568; margin-top: 8px; }
          .content { padding: 8px 24px; }
          .section { margin-bottom: 32px; }
          .section-title { font-family: 'Bebas Neue', sans-serif; font-size: 18px; letter-spacing: 1px; color: #00c864; margin-bottom: 10px; }
          .body-text { font-size: 14px; color: #8899aa; line-height: 1.7; font-weight: 300; }
          .body-text + .body-text { margin-top: 10px; }
          ul { list-style: none; margin-top: 8px; display: flex; flex-direction: column; gap: 6px; }
          ul li { font-size: 14px; color: #8899aa; line-height: 1.6; font-weight: 300; padding-left: 16px; position: relative; }
          ul li::before { content: '–'; position: absolute; left: 0; color: #00c864; }
          .divider { height: 1px; background: #1a2030; margin-bottom: 32px; }
          a.back { display: inline-flex; align-items: center; gap: 6px; font-size: 13px; color: #8896a8; text-decoration: none; margin-bottom: 24px; transition: color 0.2s; }
          a.back:hover { color: #00c864; }
          .contact-link { color: #00c864; text-decoration: none; }
          .contact-link:hover { text-decoration: underline; }
        `}</style>
  
        <div className="app">
          <div className="header">
            <div className="logo">False Nine</div>
            <div className="page-title">Terms of Service</div>
            <div className="updated">Last updated: March 2026</div>
          </div>
  
          <div className="content">
            <a href="/" className="back">← Back to app</a>
  
            <div className="section">
              <div className="section-title">1. Acceptance</div>
              <p className="body-text">By accessing or using False Nine ("the app", "the service") you agree to these Terms of Service. If you do not agree, do not use the service.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">2. The service</div>
              <p className="body-text">False Nine provides football predictions, statistics, and related content for the Premier League, Championship and FA Cup. Predictions are generated by a statistical model and are provided for entertainment and informational purposes only. They do not constitute financial, betting or gambling advice. We make no guarantee of accuracy.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">3. Accounts</div>
              <p className="body-text">You must provide a valid email address to create an account. You are responsible for maintaining the security of your account credentials. You must not share your account with others or use another person's account.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">4. Subscriptions and billing</div>
              <p className="body-text">False Nine offers a free tier and a paid Pro tier. Pro subscriptions are billed monthly. Payments are processed securely by Stripe.</p>
              <p className="body-text">Your subscription will automatically renew each month unless cancelled. You can cancel at any time via the Account page. Cancellation takes effect at the end of the current billing period — you will retain Pro access until then.</p>
              <p className="body-text">We reserve the right to change pricing with reasonable notice. We will notify you by email before any price change affects your subscription.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">5. Refunds</div>
              <p className="body-text">We do not offer refunds for partial billing periods. If you believe you have been charged in error, contact us at <a href="mailto:george.falsenine@outlook.com" className="contact-link">george.falsenine@outlook.com</a> within 14 days of the charge.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">6. Acceptable use</div>
              <p className="body-text">You agree not to:</p>
              <ul>
                <li>Scrape, copy or redistribute any data or content from False Nine</li>
                <li>Attempt to reverse engineer or interfere with the service</li>
                <li>Use the service for any unlawful purpose</li>
                <li>Create multiple accounts to circumvent free tier limits</li>
              </ul>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">7. Intellectual property</div>
              <p className="body-text">All content, predictions, data displays and design elements on False Nine are owned by us or our data providers. You may not reproduce or redistribute them without permission.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">8. Disclaimers</div>
              <p className="body-text">The service is provided "as is". We make no warranties regarding uptime, accuracy of predictions, or fitness for any particular purpose. Statistical predictions are inherently uncertain — past model performance does not guarantee future accuracy.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">9. Limitation of liability</div>
              <p className="body-text">To the fullest extent permitted by law, False Nine shall not be liable for any indirect, incidental or consequential damages arising from your use of the service. Our total liability to you shall not exceed the amount you paid us in the 12 months preceding any claim.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">10. Termination</div>
              <p className="body-text">We reserve the right to suspend or terminate your account if you breach these Terms. You may delete your account at any time by contacting us at <a href="mailto:george.falsenine@outlook.com" className="contact-link">george.falsenine@outlook.com</a>.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">11. Governing law</div>
              <p className="body-text">These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">12. Changes to these terms</div>
              <p className="body-text">We may update these Terms from time to time. Continued use of the service after changes constitutes acceptance. We will notify you of significant changes by email.</p>
            </div>
  
            <div className="divider" />
  
            <div className="section">
              <div className="section-title">13. Contact</div>
              <p className="body-text"><a href="mailto:george.falsenine@outlook.com" className="contact-link">george.falsenine@outlook.com</a></p>
            </div>
          </div>
        </div>
      </>
    )
  }